# Generated by Django 3.2.9 on 2023-01-09 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('General', '0001_initial'),
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.item', verbose_name='review_food_relation'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='review_user_relation'),
        ),
        migrations.AddField(
            model_name='feed',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_offer', to='Products.collection'),
        ),
        migrations.AddField(
            model_name='feed',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='General.mediafile'),
        ),
        migrations.AddField(
            model_name='feed',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='home_images', to='General.MediaFile'),
        ),
        migrations.AddField(
            model_name='feed',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_item', to='Products.item'),
        ),
        migrations.AddField(
            model_name='feed',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='home_items', to='Products.Item'),
        ),
        migrations.AddField(
            model_name='feed',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='General.Review'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.state'),
        ),
        migrations.AddField(
            model_name='ads',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.item', verbose_name='ads_food_relation'),
        ),
        migrations.AddField(
            model_name='ads',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.mediafile', verbose_name='ads_image'),
        ),
        migrations.AddField(
            model_name='ads',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.adstype'),
        ),
    ]
