# Generated by Django 3.2.9 on 2023-01-09 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Settings', '0001_initial'),
        ('General', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(blank=True, null=True)),
                ('lanme', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('streetAdd1', models.TextField(blank=True, null=True)),
                ('streetAdd2', models.TextField(blank=True, null=True)),
                ('zipCode', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.city', verbose_name='deliver_address_city_realtion')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.country', verbose_name='deliver_address_country_realtion')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.state', verbose_name='deliver_address_state_realtion')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitType', models.IntegerField(choices=[(1, '%'), (2, 'number')], default=1)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.extra')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, null=True)),
                ('mobile', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='transaction_user_relation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('item_price', models.FloatField(blank=True, default=0, null=True)),
                ('extras_price', models.FloatField(blank=True, default=0, null=True)),
                ('total_price', models.FloatField(blank=True, default=0, null=True)),
                ('extras', models.ManyToManyField(blank=True, to='Products.Extra')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.item', verbose_name='order_items_relation')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('billNo', models.IntegerField(default=0)),
                ('receiptNo', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'Preparing'), (3, 'delivering'), (4, 'delivered')], default=1)),
                ('isActive', models.BooleanField(default=False)),
                ('identifier', models.TextField(blank=True, null=True)),
                ('order_number', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('taxAmount', models.FloatField(blank=True, null=True)),
                ('shipAmount', models.FloatField(blank=True, null=True)),
                ('extraAmount', models.FloatField(blank=True, null=True)),
                ('couponAmount', models.FloatField(blank=True, null=True)),
                ('discountAmount', models.FloatField(blank=True, null=True)),
                ('grandAmount', models.FloatField(blank=True, null=True)),
                ('cashBackReward', models.IntegerField(blank=True, null=True)),
                ('totalWeight', models.FloatField(blank=True, null=True)),
                ('isPaid', models.BooleanField(blank=True, default=False, null=True)),
                ('isTransactionConfirmed', models.BooleanField(blank=True, default=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True, null=True)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('DeliveryAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.deliveraddress', verbose_name='order_delivery_address_realtion')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Settings.coupons')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Settings.currency')),
                ('deliveryPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_person_realtion', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.discount')),
                ('extras', models.ManyToManyField(blank=True, to='Order.ExtraOrder')),
                ('items', models.ManyToManyField(blank=True, to='Order.OrderItem', verbose_name='order_items_relation')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Settings.tax')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.transaction', verbose_name='order_transaction_realtion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='order_user_relation')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('extra', models.ManyToManyField(blank=True, to='Products.Extra')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.item', verbose_name='cart_items_relation')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('items', models.ManyToManyField(to='Order.CartItem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
