# Generated by Django 3.2.9 on 2023-01-09 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuickOrder', '0001_initial'),
        ('General', '0001_initial'),
        ('Settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('coverImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('coverImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.mediafile', verbose_name='extra_cover_image')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isFeatured', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('isDeliverable', models.BooleanField(default=False)),
                ('newPrice', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('avgRating', models.IntegerField(default=0)),
                ('servings', models.IntegerField(default=1)),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('packageCount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('unit', models.IntegerField(choices=[(1, 'g'), (2, 'kg'), (3, 'lbs')], default=1)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.attribute')),
                ('attributeItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.attributeitem')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('items', models.ManyToManyField(blank=True, to='Products.VariantItem')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('typeOfOffer', models.IntegerField(choices=[(1, 'percentage'), (2, 'amount')], default=1)),
                ('value', models.FloatField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('endAt', models.DateTimeField(blank=True, null=True)),
                ('coverImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.mediafile')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Products.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isFeatured', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('isParent', models.BooleanField(default=False)),
                ('coverImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.mediafile', verbose_name='item_category_cover_image')),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.itemcategory', verbose_name='item_category_item_category_relation')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.itemcategory', verbose_name='item_cat_item_relation'),
        ),
        migrations.AddField(
            model_name='item',
            name='coverImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_cover_image', to='General.mediafile'),
        ),
        migrations.AddField(
            model_name='item',
            name='diets',
            field=models.ManyToManyField(blank=True, to='QuickOrder.Diet'),
        ),
        migrations.AddField(
            model_name='item',
            name='extra',
            field=models.ManyToManyField(blank=True, to='Products.Extra'),
        ),
        migrations.AddField(
            model_name='item',
            name='foodTypes',
            field=models.ManyToManyField(blank=True, to='QuickOrder.FoodType'),
        ),
        migrations.AddField(
            model_name='item',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='General.MediaFile', verbose_name='item_gallery_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemAttribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.itemattr', verbose_name='item_item_attr'),
        ),
        migrations.AddField(
            model_name='item',
            name='nutritions',
            field=models.ManyToManyField(blank=True, to='Products.Nutrition'),
        ),
        migrations.AddField(
            model_name='item',
            name='relatedProduct',
            field=models.ManyToManyField(blank=True, related_name='_Products_item_relatedProduct_+', to='Products.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Settings.tax', verbose_name='item_tax'),
        ),
        migrations.AddField(
            model_name='item',
            name='variant',
            field=models.ManyToManyField(blank=True, to='Products.Variant'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLiked', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='extra',
            name='extraGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.extragroup', verbose_name='extra_extra_group_relation'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isFeatured', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('coverImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.mediafile', verbose_name='item_category_cover_image')),
                ('foods', models.ManyToManyField(to='Products.Item')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.item'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='items',
            field=models.ManyToManyField(blank=True, to='Products.AttributeItem'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.attributenames'),
        ),
    ]
